class GraphQlQuery {
  static String productQuery(String url) {
    return ''' 
    query CategoryByUrl {\n  site {\n    route(path: \"/$url/\") {\n      node {\n        id\n        ... on Category {\n          name\n          entityId\n          description\n          products {\n            edges {\n          node {\n            name\n            sku\n            entityId\n\t\t\tprices {\n\t\t\t\tprice {\n\t\t\t\t  value\n\t\t\t\t  currencyCode\n\t\t\t\t}\n\t\t\t  }\n\t\t\t  description\n          images {\n            edges {\n              node {\n                url(width: 500, height: 500)\n              }\n            }\n          }\n          brand {\n            name\n          }\n\t\t  productOptions {\n            edges {\n              node {\n                entityId\n                displayName\n                isRequired\n                ... on MultipleChoiceOption {\n                  values {\n                    edges {\n                      node {\n                        entityId\n                        label\n                        \n                      }\n                    }\n                  }\n                }\n              }\n            }\n          }\n          }\n        }\n          }\n        }\n      }\n    }\n  }\n}
    ''';
  }
  static String searchQuery(String key) {
    return ''' 
    query {\n  site {\n    search {\n      searchProducts(\n        filters: {\n          searchTerm: \"$key\"\n        }\n        sort: A_TO_Z\n      ) {\n        products(first: 2) {\n          edges {\n          node {\n            name\n            sku\n            entityId\n\t\t\tprices {\n\t\t\t\tprice {\n\t\t\t\t  value\n\t\t\t\t  currencyCode\n\t\t\t\t}\n\t\t\t  }\n\t\t\t  description\n          images {\n            edges {\n              node {\n                url(width: 500, height: 500)\n              }\n            }\n          }\n          brand {\n            name\n          }\n\t\t  productOptions {\n            edges {\n              node {\n                entityId\n                displayName\n                isRequired\n                ... on MultipleChoiceOption {\n                  values {\n                    edges {\n                      node {\n                        entityId\n                        label\n                        \n                      }\n                    }\n                  }\n                }\n              }\n            }\n          }\n          }\n        }\n        }\n      }\n    }\n  }\n}
    ''';
  }
  static String productWithHexColorQuery(String key){
    return ''' 
    query SingleProduct {\n  site {\n    products (entityIds: [${key}]) {\n      edges {\n          node {\n            name\n            sku\n            entityId\n\t\t\tprices {\n\t\t\t\tprice {\n\t\t\t\t  value\n\t\t\t\t  currencyCode\n\t\t\t\t}\n\t\t\t  }\n\t\t\t  description\n          images {\n            edges {\n              node {\n                url(width: 500, height: 500)\n              }\n            }\n          }\n          brand {\n            name\n          }\n\t\t  productOptions {\n            edges {\n              node {\n                entityId\n                displayName\n                isRequired\n                ... on MultipleChoiceOption {\n                  values {\n                    edges {\n                      node {\n                        entityId\n                        label\n                        ... on SwatchOptionValue {\n                           hexColors\n                         }\n                      }\n                    }\n                  }\n                }\n              }\n            }\n          }\n          }\n        }\n    }\n  }\n}
    ''';
  }
}
